apiVersion: v1
kind: Secret
metadata:
  name: teaching-scheduler-secrets
  labels:
    app: teaching-scheduler
type: Opaque
# These values should be base64 encoded and replaced in a secure manner
# Do not commit actual secrets to version control
# Example of how to create these values:
# echo -n "your-actual-url" | base64
stringData:
  supabase-url: "https://tdcxyktnqtdeyvcpogyg.supabase.co"
  # Replace this with your actual key, using Kubernetes secrets management or
  # a secure CI/CD pipeline to inject the real value in production
  supabase-key: "your-supabase-key-here"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-registry
  labels:
    app: teaching-scheduler
type: kubernetes.io/dockerconfigjson
# Replace with your actual GitHub container registry credentials
# kubectl create secret docker-registry github-registry --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME --docker-password=YOUR_GITHUB_TOKEN \
#   --docker-email=YOUR_EMAIL -o yaml
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "base64-encoded-username:token"
        }
      }
    } 