version: '3.8'

services:
  # Teaching Scheduler Next.js application - Production
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: teaching-scheduler:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: ${REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MCP Monitor Server - Production
  mcp-monitor:
    image: node:18-alpine
    working_dir: /mcp
    command: npx @anthropic-ai/mcp-server console
    volumes:
      - ../mcp:/mcp
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MCP_PORT=3001
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

networks:
  default:
    driver: bridge 