version: '3.8'

services:
  # Teaching Scheduler Next.js application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder # Use the builder stage for development
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    depends_on:
      - mcp-console

  # MCP Console Monitor Server
  mcp-console:
    image: node:18-alpine
    working_dir: /mcp
    command: npx @anthropic-ai/mcp-server console
    volumes:
      - ../mcp:/mcp
    ports:
      - "3001:3001"
    environment:
      - MCP_PORT=3001
    restart: unless-stopped

  # Production deployment setup (optional, uncomment to use)
  # app-prod:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - SUPABASE_URL=${SUPABASE_URL}
  #     - SUPABASE_KEY=${SUPABASE_KEY}
  #   restart: unless-stopped
  #   depends_on:
  #     - mcp-monitor

  # MCP Docker Server for container management
  mcp-docker:
    image: python:3.12-alpine
    working_dir: /mcp
    command: pip install docker-mcp && uvx docker-mcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../mcp:/mcp
    ports:
      - "3002:3002"
    environment:
      - MCP_PORT=3002
    restart: unless-stopped 